#include "rtp.h"
#include <cstdio>
#include <cassert>
#include <cstring>
#include <vector>
#include <fstream>
#include <string>
using namespace esphome::rtsp_server;

static std::vector<uint8_t> load(const char *p) {
  std::ifstream f(p, std::ios::binary);
  return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}

struct Collector : RtpSender {
  std::vector<std::vector<uint8_t>> pkts;
  void send_rtp(StreamKind, uint8_t *buf, size_t n) override {
    pkts.push_back(std::vector<uint8_t>(buf + 4, buf + 4 + n));
  }
};

// Reassemble the way an RFC 2435 receiver does, and check the result matches
// the scan data of the original JPEG exactly.
static void check(const std::string &path, uint8_t want_type, size_t mtu) {
  auto jpg = load(path.c_str());
  assert(!jpg.empty());
  JpegInfo info = parse_jpeg(jpg.data(), jpg.size());
  assert(info.valid);
  assert(info.width == 320 && info.height == 240);
  assert(info.type == want_type);
  assert(info.luma_table && info.chroma_table);

  Collector c;
  MjpegPacketizer p(mtu, 26, 7);
  assert(p.packetize(jpg.data(), jpg.size(), 12345, &c));
  assert(!c.pkts.empty());

  std::vector<uint8_t> scan;
  uint8_t qt[128]; bool have_qt = false;
  for (size_t i = 0; i < c.pkts.size(); i++) {
    auto &d = c.pkts[i];
    assert(d.size() <= mtu);
    assert((d[1] & 0x7F) == 26);
    assert(((d[1] & 0x80) != 0) == (i == c.pkts.size() - 1));   // marker on last only
    uint32_t ts = (d[4]<<24)|(d[5]<<16)|(d[6]<<8)|d[7];
    assert(ts == 12345);                                        // one timestamp per frame

    const uint8_t *j = d.data() + 12;
    uint32_t off = (j[1]<<16)|(j[2]<<8)|j[3];
    assert(off == scan.size());                                 // fragment offsets are contiguous
    assert(j[4] == want_type);
    assert(j[5] == 255);                                        // Q=255 -> tables in band
    assert(j[6] == 320/8 && j[7] == 240/8);
    const uint8_t *body = j + 8;
    if (i == 0) {
      assert(body[0] == 0 && body[1] == 0);
      size_t tlen = (body[2]<<8)|body[3];
      assert(tlen == 128);
      memcpy(qt, body + 4, 128); have_qt = true;
      body += 4 + 128;
    }
    size_t used = (size_t)(body - d.data());
    scan.insert(scan.end(), body, static_cast<const uint8_t *>(d.data()) + d.size());
    (void)used;
  }
  assert(have_qt);
  assert(memcmp(qt, info.luma_table, 64) == 0);
  assert(memcmp(qt + 64, info.chroma_table, 64) == 0);
  assert(scan.size() == info.scan_len);
  assert(memcmp(scan.data(), info.scan, info.scan_len) == 0);
  printf("%-10s type=%u %ux%u  %zu pkts (mtu %zu)  scan %zu B reassembled byte-exact\n",
         path.c_str(), want_type, info.width, info.height, c.pkts.size(), mtu, scan.size());
}

int main(int argc, char **argv) {
  // Fixtures are generated by tests/make_jpeg_fixtures.py into argv[1].
  const std::string dir = argc > 1 ? argv[1] : ".";
  auto path = [&](const char *n) { return dir + "/" + n; };

  check(path("f420.jpg"), 1, 1400);
  check(path("f422.jpg"), 0, 1400);
  check(path("f420.jpg"), 1, 600);     // heavier fragmentation
  check(path("f420.jpg"), 1, 12000);   // single packet after the header

  // 4:4:4 has no RFC 2435 type -> must be rejected, not mis-sent.
  auto j444 = load(path("f444.jpg").c_str());
  assert(!parse_jpeg(j444.data(), j444.size()).valid);
  Collector c; MjpegPacketizer p(1400, 26, 1);
  assert(!p.packetize(j444.data(), j444.size(), 0, &c));
  assert(c.pkts.empty());
  printf("f444.jpg   correctly rejected (4:4:4 has no RFC 2435 type)\n");

  // Garbage must not crash or emit.
  std::vector<uint8_t> junk(500, 0xAB);
  assert(!parse_jpeg(junk.data(), junk.size()).valid);
  uint8_t trunc[] = {0xFF,0xD8,0xFF,0xDB,0x00,0x43};
  assert(!parse_jpeg(trunc, sizeof(trunc)).valid);
  printf("malformed input rejected safely\n");

  printf("\nall MJPEG checks passed\n");
  return 0;
}
